- ignore:
    name: "Use newtype instead of data"
- ignore:
    name: "Use const"
- ignore:
    name: "Use &&"
- ignore:
    name: "Use ++"
- ignore:
    name: "Use unless"
- ignore:
    name: "Use record patterns"
- ignore:
    name: "Use getChar"
