resolver: lts-18.16

packages:
- feedback

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: f30fe0e4d2a0fa036967ffe17538b60e5f9861f5
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo
- github: NorfairKing/autodocodec
  commit: b18d6e51382d0e31d3c63d6658e37a22fad82256
  subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml
nix:
  enable: true
  shell-file: shell.nix
