name:                feedback
version:             0.0.0.0
github:              "NorfairKing/feedback"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2022 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - async
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - cursor
  - envparse
  - fsnotify
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - process
  - safe-coloured-text
  - safe-coloured-text-terminfo
  - text
  - time
  - typed-process
  - unliftio
  - yaml

executables:
  feedback:
    main: Loop.main
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - feedback
  feedback-test:
    main: Test.main
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - feedback
