name: feedback
version: 0.0.0.0
github: "NorfairKing/feedback"
license: GPL-3.0-only
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2022 Tom Sydney Kerckhove"
synopsis: Declarative feedback loop manager 

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - autodocodec-yaml >= 0.2
  - bytestring
  - conduit
  - containers
  - envparse
  - fsnotify
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - safe-coloured-text
  - safe-coloured-text-layout
  - text
  - time
  - typed-process
  - unix
  - unliftio
  - yaml
  when:
  - condition: os(windows)
    then:
      dependencies:
        - Win32 >= 2.13.2
    else:
      dependencies:
        - safe-coloured-text-terminfo

executables:
  feedback:
    main: Loop.main
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -optP-Wno-nonportable-include-path # For macos
    # -N3: Use two threads, because we only need three threads:
    # 1. FS Notify listener
    # 2. Wait for an event
    # 3. Wait for the process
    #
    # -I0: Turn off idle GC because we GC manually between loops.
    - '"-with-rtsopts=-N3 -I0"'
    dependencies:
    - feedback
  feedback-test:
    main: Test.main
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - feedback
